import { Main } from '@/components/main/Main';
import { Nav } from '@/components/nav/Nav';
import GlobalStyle from '@/styles/GlobalStyle';
import type { AppProps } from 'next/app';
import Head from 'next/head';

export default function App({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<title>WOOWA SHOP</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<GlobalStyle />
			<Nav />
			<Main>
				<Component {...pageProps} />
			</Main>
		</>
	);
}
